// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChainlinkClient is an autogenerated mock type for the Client type
type ChainlinkClient struct {
	mock.Mock
}

// TriggerJob provides a mock function with given fields: jobId, data
func (_m *ChainlinkClient) TriggerJob(jobId string, data []byte) error {
	ret := _m.Called(jobId, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(jobId, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
